INSERT INTO zasoby (tytul, autor, wydawnictwo, ilosc, gatunek)
VALUES
('Służąca','Alicja Sinicka', 4, 12, 6),
('Sapiens. Od zwierząt do bogów','Yuval Noah Harari', 1, 7, 2),
('Cień i kość','Leigh Bardugo', 11, 5, 10),
('Siedem sióstr','Lucina Riley', 8, 9, 9),
('Halny','Remigiusz Mróz', 6, 10, 10),
('Czuły narrator','Olga Tokarczuk', 3, 15, 6),
('Pięć Stawów. Dom bez adresu','Beata Sabała-Zielińska', 2, 11, 10),
('Metro 2033','Dmitry Glukohvsky', 6, 20, 1),
('Kult','Łukasz Orbitowski', 7, 6, 11),
('Molly','Agnieszka Lingas-Łoniewska', 2, 7, 3),
('Pokusa Gangstera','Anna Wolf', 9,8, 4),
('Lucca','Sarah Brienne', 6, 5, 5),
('Diuna','Frank Herbert', 8, 10, 9),
('Autostopem przez życie','Przemysław Skokowski', 10, 7, 12),
('Cień Wiatru','Carlos Ruiz Zafon', 1, 5, 7),
('Malowany ptak','Jerzy Kosiński', 4, 8, 3),
('Droga Królów','Brandon Sanderson', 2, 14, 9),
('Zabić drozda','Nelle Harper Lee', 9, 6, 4);
